dry-rb/dry-struct

Gemfile, dry-struct.gemspec, lib/dry/struct/version.rb, spec/dry/struct/version_spec.rb, spec/spec_helper.rb
- Bump version to 0.0.1 for first rubygem release
- Update dry-types dependency
---
For some reason dry-configurable breaks if I add a require for `dry/struct/version` in the gemspec:
```diff
diff --git i/dry-struct.gemspec w/dry-struct.gemspec
index 4e3e085..91acbb7 100644
--- i/dry-struct.gemspec
+++ w/dry-struct.gemspec
@@ -1,5 +1,8 @@
+root = File.expand_path(__dir__)
+require File.join(root, 'lib/dry/struct/version.rb')
+
Gem::Specification.new do |spec|
spec.name          = 'dry-struct'
spec.version       = '0.0.0'
```
the specs fail before even running. Specifically I run into
`'initialize': wrong number of arguments (given 3, expected 0)` from
dry-configurable-0.1.6/lib/dry/configurable.rb:53
As a stopgap I am opening an issue with dry-configurable for this error
and also opening …
=> Bump version to 0.0.1

lib/dry/struct.rb, lib/dry/struct/class_interface.rb, lib/dry/struct/value.rb, spec/spec_helper.rb
There was a problem with variables @schema and @constructor_type
when using and loading dry-struct. The place where those should be initialized -
missed. After experimenting a bit I found on which cases we use  variables
without initialization:
- when we extending Dry::Struct with ClassInterface
- when we inheriting any class from Dry::Struct or its successor
This all caused by the rule that class ivars are not shared with
successors. So we need to initialize them in a hook or like that.
In my solution:
- @constructor_type is initialized by its writer in body of Dry::Struct class
- @schema is initialized in ```extended``` and ```inherited``` hooks
Also there was a huge warning "loading in progress, circular require..."
in lib/struct/value.rb, now - seems fixed.
Closes …
=> Fix warnings "instance variable not initialized"

lib/dry/struct/class_interface.rb
This adds `constrained?` predicate to structs which recently was merged into dry-t. I'll add the specs later today, but we need this finished before releasing the gem.
=> [WIP] Add constrained? to class interface

Gemfile, lib/dry/struct.rb, lib/dry/struct/class_interface.rb
- dry-logic is now pegged to the master branch on github until dry-types and dry-logic are released
- The default constructor_type is now `:permissive` (which is the same as the old behavior but renamed to make room for the real strict constructor_type)
- Add `success` and `failure` to the class interface of dry struct to conform with the interface that Dry::Types::Definition requires
=> Update dry-struct to latest dry-types

lib/dry/struct/class_interface.rb, spec/dry/types/struct_spec.rb
According to LSP from SOLID, subclasses should preserve the same interface as superclass. 
Thus, it's needed to `Dry::Struct` to return an original subclass instance, not an instance coerced to a superclass.
=> Return itself if an object is an instance of subclass

.yardopts, Rakefile, dry-struct.gemspec, lib/dry/struct.rb, lib/dry/struct/class_interface.rb, lib/dry/struct/errors.rb, lib/dry/struct/hashify.rb, lib/dry/struct/value.rb
I am continuing my work on documenting `dry-*` gems that I’ve started in dry-rb/dry-types#166. 
Now I have documented some `dry-struct` code. This time with more detailed comments and (my favorite part) clear examples for different constructor types and given input.
=> YARD documentation for Dry::Struct

CHANGELOG.md, lib/dry/struct/class_interface.rb, spec/dry/struct_spec.rb
#11 
@solnic I added the ArgumentError, by checking when no argument is added to the `new` method, and if the `type` of the `Struct` is a `string`
=> Raise ArgumentError when attribute type is a string and no value is supplied

.travis.yml, dry-struct.gemspec, lib/dry/struct.rb, spec/dry/struct_spec.rb, spec/shared/struct.rb
@solnic @flash-gordon 
This restricts the use of weak and symbolize in the constrictor type with the use of the latest `dry-core` release
Happens that with the latest version of `dry-types` some specs changed the location and one of them it was failing https://github.com/dry-rb/dry-types/blob/master/lib/dry/types/spec/types.rb#L81. This test is heavily used in `dry-types` so I thought to remove it was not an option, so I came with a little hackey solution 😄 
Hope this change helps.
=> Restrict use of weak and symbolize for constructor type

lib/dry/struct.rb, spec/dry_spec.rb
I originally [posted this as an idea on Discourse](https://discourse.dry-rb.org/t/dry-struct-factory-method-easier-type-constructor/365). @timriley expressed some interest and 2 other people "liked" the idea (whatever that's worth), but there was no other feedback. 
So before I go through the effort of writing YARD docs, adding specs etc. here's a barebones PR for further discussion. I'll also copy over the description from Discourse, so everything's in one place:
I've been playing around with `dry-struct` yesterday, and found nothing quite as compact as the following shorthand used with normal Ruby structs:
```ruby
Person = Struct.new(:age, :name)
```
Since there are already some capitalized methods that act like "type constructors" in `dry-rb`, I added a "factory method", `Dry.Struct`: …
=> Add Dry.Struct constructor method

CONTRIBUTING.md, lib/dry/struct/class_interface.rb, spec/dry/struct_spec.rb
As discussed in https://github.com/dry-rb/dry-struct/issues/2
```ruby
module Types
include Dry::Types.module
end
user_class = Class.new(Dry::Struct) do
attribute :name, Types::Coercible::String
attribute :age, Types::Coercible::Int
attribute :address do
attribute :city, Types::Coercible::String
attribute :zipcode, Types::Coercible::String
end
end
user = user_class.new(
name: :Jane,
age: '21',
address: {
city: 'NYC',
zipcode: 123
}
)
user.address.city
user.address.zipcode
```
You can also pass a superclass type, this will be used as the superclass of the nested type that is built, i.e.
```ruby
module Types
include Dry::Types.module
end
class BaseAddress < Dry::Struct
attribute :street, 'strict.string'
end
user_class = Class.new(Dry::Struct) do
attribute :name, Types::Coercible::String …
```
=> Support nested structs by passing a block to Dry::Struct.attribute

Gemfile, lib/dry/struct.rb, lib/dry/struct/class_interface.rb, spec/dry/struct_spec.rb, spec/dry_spec.rb, spec/shared/struct.rb
This removes `constructor_type` in favor of these two methods:
1. `Struct.transform_types`—transforms all _new_ attribute types with an arbitrary block (uses `Dry::Types::Schema#with_type_transform`).
1. `Struct.transform_keys`—transforms input keys with a block (uses `Dry::Types::Hash#with_key_transform`).
See https://github.com/dry-rb/dry-types/pull/231
For unknown keys it is possible to make the underlying schema _strict_:
```ruby
class Book < Dry::Struct
input input.strict
attribute :title, Types::Strict::String
end
Book.new(title: "The Old Man and the Sea", foo: :bar) 
```
You always can create a base class for strict structs:
```ruby
StrictStruct = Class.new(Dry::Struct) { input input.strict }
```
Also, individual attributes can be omitted with adding `omittable: true` to theirs …
=> Replace constructor_type with types/keys transformations

.travis.yml, dry-struct.gemspec, lib/dry/struct.rb, lib/dry/struct/class_interface.rb, spec/dry/struct_spec.rb
Previously, we stored values in separate instance variables, this changes behavior in favor of using a single ivar. Even for a struct of 3 attributes, it adds roughly 12% to initialization speed.
```
Warming up --------------------------------------
benchmark     8.476k i/100ms
Calculating -------------------------------------
benchmark     86.125k (± 5.9%) i/s -    432.276k in   5.038505s
Warming up --------------------------------------
benchmark     9.449k i/100ms
Calculating -------------------------------------
benchmark     97.353k (± 5.8%) i/s -    491.348k in   5.067257s
```
For 15 attributes it's ~20%:
```
Warming up --------------------------------------
benchmark     1.990k i/100ms
Calculating -------------------------------------
benchmark     20.737k (± 4.7%) i/s - …
```
=> Store values within a signle ivar

bin/console
@flash-gordon I was playing with it and notice `bin/console` was not working
=> Add missing require for bin/console

lib/dry/struct/class_interface.rb, spec/dry/struct_spec.rb
@flash-gordon @solnic @AMHOL 
Way to infer default values for nested attributes when calling `new` and `call`.
This will simplify a lot `dry-configurable` https://github.com/dry-rb/dry-configurable/pull/48 avoiding the need for creating the default values
=> build default attributes when calling #new and #call without arguments

lib/dry/struct/class_interface.rb
@flash-gordon 
It was conflicting when passing an attribute of type `Type::Hash`
Instead of checking if the type has the method `schema` we check that the type is `Dry::Struct`
=> do not relay on respond_to? :schema

lib/dry/struct/struct_builder.rb, spec/dry/struct/attribute_dsl/nested_struct_spec.rb
```ruby
Data = Module.new
module Namespace
class Struct < Dry::Struct
attribute(:data) do
attribute(:num, Dry::Types::Integer)
end
end
end # => Dry::Struct::Error
```
`Dry::Struct::Error: Can't create nested attribute - Namespace::Struct::Data already defined`
This pr restricts constant lookup to class scope [`Dry::Struct::StructBuilder#check_name`](https://github.com/dry-rb/dry-struct/blob/master/lib/dry/struct/struct_builder.rb#L63)
=> Restrict constant lookup

lib/dry/struct.rb
This request avoids the unnecessary `rescue KeyError` within  [`Dry::Struct#[]`](https://github.com/noname00000123/dry-struct/blob/1bc33d50c7b4615a328ab9f496709e6f37c82f62/lib/dry/struct.rb#L122)  raising within the block passed to `@attributes.fetch(name)` instead; ~300x faster than the current implementation. 
```ruby
require 'benchmark/ips'
def self.implementation
{}.fetch(:key)
rescue KeyError
1 # raise(::StandardError, :key)
end
def self.revision
{}.fetch(:key) { 1 } # { raise(::StandardError, :key) }
end
#
Benchmark.ips do |x |
x.report('implementation') { implementation() }
x.report('revision') { revision() }
x.compare!
end
```
=> [Enhancement] Raise MissingAttributeError within block

.gitignore, lib/dry/struct/class_interface.rb, spec/dry/struct/attribute_dsl/definition_spec.rb, spec/shared/struct.rb, spec/spec_helper.rb
This utilizes an already defined method called `Struct.attribute?`. It now shows a warning if you use it for checking key presence suggesting to use `Struct.has_attribute?` as a replacement.
=> Add DSL for defining omittable keys

.travis.yml, CHANGELOG.md, Gemfile, dry-struct.gemspec, lib/dry/struct.rb, lib/dry/struct/class_interface.rb, spec/dry/struct/attribute_dsl/definition_spec.rb, spec/dry/struct/attribute_dsl/nested_array_spec.rb, spec/dry/struct_spec.rb, spec/dry_spec.rb, spec/shared/struct.rb, spec/spec_helper.rb
See https://github.com/dry-rb/dry-types/pull/286
This also replaces Struct.input with Struct.schema since now schema is not an abstract thing anymore. In ROM we may want to use something like `schema schema.constructor(&:itself)` to make struct constructors work faster when no type checks needed.
=> Sync with schema updates from dry-types

lib/dry/struct/class_interface.rb
The examples in the docs are not working, because there is no `array` method defined.
=> Fix documentation: array cannot be used

lib/dry/struct/class_interface.rb
Since the methods `success` and `failure` were introduced they should be used to keep the code DRY.
=> Use success and failure methods to keep it DRY

lib/dry/struct/hashify.rb
`Dry::Struct` requires ruby >= 2.4, so the verification is
not longer needed. With this change we had 2 gains:
1.- Less code executed (less code to maintain!!)
2.- More coverage (hashify.rb now it's 100%)
=> Remove not needed branch about ruby 2.4

.travis.yml, Gemfile, lib/dry/struct.rb, spec/dry/struct/pattern_matching_spec.rb, spec/spec_helper.rb
This is Ruby 2.7+
Example:
```ruby
class User < Dry::Struct
attribute :first_name, 'string'
attribute :last_name, 'string'
attribute(:address) do
attribute :city, 'string'
attribute :street, 'string'
end
end
case user
in User({ first_name: 'Jack' })
"It's Jack"
in User({ first_name: 'Alice' | 'Carol' })
'Alice or Carol'
in User({ first_name:, last_name: 'Doe' })
"DOE, #{first_name.upcase}"
in User({ first_name:, last_name: 'Doe' })
"DOE, #{first_name.upcase}"
in User({ first_name:, address: User::Address({ street: 'Downing street' }) })
"PM is #{first_name}"
end
```
With dry-monads 1.3:
```ruby
module Test
class Operation
include Dry::Monads[:result]
def call(result)
case result
in Success(User({ first_name: }))
"Name is #{first_name}"
in Failure[:not_found]
"Wasn't found"
in …
```
=> Add experimental support for pattern matching

.travis.yml, spec/spec_helper.rb
With this, we can use the suite locally if not using ruby 2.7 nor
adding the --exclude_pattern flag
=> Exclude specs using ruby 2.7 on spec_helper

lib/dry/struct.rb, spec/dry/struct/pattern_matching_spec.rb
Hi,
How about using  deconstruct_keys instead of deconstruct for pattern matching support?
=> Use deconstruct_keys instead of deconstruct

dry-struct.gemspec, lib/dry/struct.rb, lib/dry/struct/class_interface.rb, spec/shared/struct.rb
This PR switches dry-struct to use [immutable equalizer](https://github.com/dry-rb/dry-equalizer/releases/tag/v0.3.0) by default. We always treated structs as immutable objects. The only actual reason structs are not frozen is calling `.freeze` affects performance. That said, this may be a breaking change for some users of dry-struct. To use the mutable equalizer, subclass `Dry::Struct` and include a new module:
```ruby
class MutableStruct < Dry::Struct
include Dry::Equalizer(:__attributes__, inspect: false)
end
```
=> Switch to immutable equalizer

lib/dry/struct.rb, lib/dry/struct/class_interface.rb, lib/dry/struct/struct_builder.rb, lib/dry/struct/value.rb, spec/dry/struct/value_spec.rb, spec/dry/struct_spec.rb, spec/shared/struct.rb
It has little use; we already treat structs as immutable objects. Making structs mutable never worked well, we always discouraged people from using them this way. In this light, having Dry::Struct::Value doesn't add anything, it's an example of defensive programming that slows code down without clear benefit. This commit deprecates Dry::Struct::Value, dry-struct 2.0 will remove it completely.
=> Deprecate Dry::Struct::Value

lib/dry/struct.rb
Because it's got overridden by Dry::Types::Builder#prepend
=> Re-define Struct.prepend

Gemfile, lib/dry/struct/class_interface.rb, lib/dry/struct/struct_builder.rb, project.yml, spec/dry/struct/attribute_dsl/definition_spec.rb, spec/dry/struct/attribute_dsl/nested_struct_spec.rb, spec/dry/struct_spec.rb, spec/shared/struct.rb, spec/spec_helper.rb
It's done in a smart way. Unless you explicitly provided a struct, transformations from the containing struct will be used. It works like this:
```ruby
class User < Dry::Struct
transform_keys(&:to_sym)
attribute :name, Types::String
attribute :address do
attribute :city, Types::String
end
end
```
However, if you do
```ruby
attribute :address, Dry::Struct do
...
end
```
^it will not convert keys for `:address`
=> Keep types and keys transformations for nested structs

lib/dry/struct.rb, lib/dry/struct/class_interface.rb, lib/dry/struct/hashify.rb, spec/dry/struct_spec.rb
It served us poorly. .to_hash is used by ruby implicitly for converting values to keywords. This is not needed for structs. As a step 1, we deprecate `#to_hash` to understand the impact of further removal. Users can define `#to_hash` at will.
=> Deprecate Struct#to_hash

docsite/source/recipes.html.md, lib/dry/struct/class_interface.rb, spec/dry/struct/compose_spec.rb
This feature would be a step towards using composition throughout dry-rb ecosystem, as we mentioned in https://github.com/dry-rb/dry-validation/pull/595 comments
=> Add struct composition

lib/dry/struct.rb, lib/dry/struct/class_interface.rb, lib/dry/struct/struct_builder.rb, lib/dry/struct/value.rb, spec/dry/struct/attribute_dsl/abstract_struct_spec.rb
Abstract struct will be used as a base class for nested structs.
```ruby
class AbstractStruct < Dry::Struct
abstract
transform_keys(&:to_sym)
def key?(key)
attributes.key?(key)
end
end
class User < AbstractStruct
attribute :name, 'string'
attribute :address do
attribute :city, 'string'
end
end
```
^here `AbstractStruct` will be the superclass of `User::Address`
=> Abstract structs

lib/dry/struct/class_interface.rb, lib/dry/struct/compiler.rb, lib/dry/struct/struct_builder.rb, spec/integration/compile_spec.rb, spec/unit/struct_spec.rb
I keep a reference to the original class in the AST because it's the only way to do it right. This shouldn't be a problem, though.
This PR also adds a struct compiler which we can reuse in dry-schema.
=> Implement Struct.to_ast

lib/dry/struct.rb, lib/dry/struct/class_interface.rb, spec/integration/struct_spec.rb
@solnic it's implicitly used by rom-changeset here https://github.com/rom-rb/rom/blob/212ccab204c49b64f8d81e03b6b3dc7c041d1182/changeset/lib/rom/changeset/update.rb#L68
It shouldn't be hard to fix if we change `auto_struct` to `false` for `original`, I'll file an issue there. For the time being, I'm rolling back the deprecation.
=> Rollback to_hash deprecation

lib/dry/struct/class_interface.rb, spec/integration/attributes_from_spec.rb, spec/shared/struct.rb
It lacked attribute readers, didn't clear attribute names cache, didn't pay attention to descendants :see_no_evil:
=> Fix Struct.attributes_from

lib/dry/struct/struct_builder.rb, spec/integration/attribute_dsl/definition_spec.rb
This adds support for inferring base class from optional structs
```ruby
class User  < Dry::Struct
attribute :address, Dry::Struct.optional do
attribute :city, 'string'
end
end
```
Resolves #156
It doesn't work in more complex cases like arrays of optionals or optional arrays but I doubt these cases are common enough to bother, there's always another way to implement them.
=> Create base class from optional structs

.gitignore, lib/dry/struct/extensions/pretty_print.rb, spec/extensions/pretty_print_spec.rb
Hello folks, found an issue in the pretty_print extension.
Without this fix `pretty_inspect` method, which is used by, for example, RSpec to display a diff, fails with `TypeError: no implicit conversion of Symbol into String`. 
Also, since pp is required by default starting Ruby 2.5 and 2.4 is EOL, maybe it actually makes sense to include this extension into the core of the gem?
=> Fix pretty_print extension

lib/dry/struct.rb
~~I had to remove `extensions` from zeitwerk's ignored list and move `PrettyPrint` to `Extensions::PrettyPrint` so that the file structure matches namespaces (otherwise Zeitwerk complains, which is expected).~~
~~I did not fully track down which specific line caused the original issue, as in, I do not know what refers to `Extensions` that cause auto-loading of that module and not finding anything (since `extensions` was ignored in the loader config).~~
~~Anyhow, I reckon this should do it and it doesn't break anything else (famous last words 🤣)~~
So, actually, adding `extensions.rb` and `extensions` dir did the trick too.
Fixes #183
=> Move PrettyPrint to Extensions namespace

lib/dry/struct/class_interface.rb, spec/shared/struct.rb
It should have worked like this from the very beginning (dry-types keeps exception instances there). I'll do some testing against my production code, just to make sure this doesn't break things.
=> Keep original error in failure object

Gemfile.devtools
Just a simple platforms qualifier to exclude it when run from JRuby.
=> byebugs currently unsupported by JRuby

lib/dry/struct.rb, lib/dry/struct/errors.rb, spec/integration/struct_spec.rb
I saw this original PR (#170) was closed due to the fork of dry-struct being deleted by the author. 
I think this is a valuable contribution that should be included (and it's a contribution I would make myself if I had come across the issue), so I'm opening this PR. I also refactored it a little bit to use kwargs.
=> Add class name to missing attribute error

Gemfile.devtools, changelog.yml, lib/dry/struct/errors.rb, lib/dry/struct/sum.rb, spec/integration/array_spec.rb, spec/spec_helper.rb
This changes the base class for `Dry::Struct::Error` to `Dry::Types::CoercionError`. It solves one of the bugs but it also makes sense in general.
=> Fix bugs with coercing input to arrays of struct types

Gemfile, lib/dry/struct/extensions.rb, lib/dry/struct/extensions/super_diff.rb, spec/extensions/super_diff_spec.rb, spec/spec_helper.rb
[super_diff](https://github.com/splitwise/super_diff/) is very useful in combination with rspec. There's a simple way to integrate an existing class: adding `attributes_for_super_diff` method is enough.
Before:
```ruby
expected: #<Test::User name="Jane" age=22>
got: #<Test::User name="Jane" age=21>
(compared using eql?)
Diff:
@@ -1 +1 @@
-#<Test::User name="Jane" age=22>
+#<Test::User name="Jane" age=21>
```
After:
```ruby
expected: #<Test::User name: "Jane", age: 22>
got: #<Test::User name: "Jane", age: 21>
(compared using eql?)
Diff:
┌ (Key) ──────────────────────────┐
│ ‹-› in expected, not in actual  │
│ ‹+› in actual, not in expected  │
│ ‹ › in both expected and actual │
└─────────────────────────────────┘
#<Test::User {
name: "Jane",
-   age: 22
+   age: 21
}>
```
To use this …
=> Add super_diff extension
